/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PROG_ICE_task_2_Q2;
import javax.swing.JOptionPane;

public class App {


 public static void main(String[] args) {
     
     String [] Days = new String[7];
     String Day;
     
     for (int i = 0; i < Days.length; i++)
     {
         Day = JOptionPane.showInputDialog("Please enter day of the week: ");
         Days[i] = Day;
     }
        JOptionPane.showMessageDialog(null , Days);
    }
}
